version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "9000:9000"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    deploy:
      placement:
        constraints: [node.role == manager]
  front:
    image: localhost:5000/front:latest
    ports:
      - "8080:8080"
    depends_on:
      - back
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
  back:
    image: localhost:5000/back:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure

volumes:
  postgres_data: